package com.opendbclient.bridge.export;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Pattern;

import com.opendbclient.bridge.result.ResultColumn;

/**
 * Writes portable {@code INSERT} statements.
 *
 * <p>Intended for moving data into another database, so the output has to be valid on databases the
 * tool has never seen. Everything emitted is standard SQL: no vendor-specific quoting, no
 * {@code UPSERT} syntax, no batch separators. Identifiers are taken verbatim from the caller, which
 * is what lets a user paste in a pre-quoted name when their database needs one.
 *
 * <p>The interesting problem is literals. Values arrive either as real numbers, or as strings that
 * were deliberately kept textual to preserve precision - a {@code BIGINT} beyond 2^53, or a
 * {@code DECIMAL} whose scale matters. Quoting those would silently turn a number into text in the
 * destination database, so a string is emitted bare when its column is numeric and the text is
 * genuinely numeric. Anything else is quoted, which also covers error markers and any other text
 * that ended up in a numeric column.
 */
public final class SqlInsertExport implements ExportTarget {

    /** Matches a decimal literal that a database will accept unquoted. */
    private static final Pattern NUMERIC_LITERAL = Pattern.compile("[-+]?\\d+(\\.\\d+)?([eE][-+]?\\d+)?");

    private final Path target;
    private final String tableName;
    private final int rowsPerStatement;
    private final String statementTerminator;

    private Writer writer;
    private List<ResultColumn> columns;
    private String columnList;
    private int rowsInBatch;
    private StringBuilder batch;

    public SqlInsertExport(Path target, String tableName, int rowsPerStatement, String statementTerminator) {
        this.target = target;
        this.tableName = tableName;
        this.rowsPerStatement = Math.max(1, rowsPerStatement);
        this.statementTerminator = statementTerminator == null || statementTerminator.isEmpty()
                ? ";"
                : statementTerminator;
    }

    @Override
    public void begin(List<ResultColumn> sourceColumns) throws IOException {
        this.columns = List.copyOf(sourceColumns);
        this.writer = new BufferedWriter(
                new OutputStreamWriter(Files.newOutputStream(target), StandardCharsets.UTF_8), 64 * 1024);

        StringBuilder names = new StringBuilder();
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) {
                names.append(", ");
            }
            names.append(columns.get(i).label());
        }
        this.columnList = names.toString();

        writer.write("-- Generated by Open DB Client\n");
        writer.write("-- " + columns.size() + " column(s), table " + tableName + "\n\n");
    }

    @Override
    public void row(List<Object> values) throws IOException {
        if (rowsInBatch == 0) {
            batch = new StringBuilder(256);
            batch.append("INSERT INTO ").append(tableName)
                    .append(" (").append(columnList).append(") VALUES\n");
        } else {
            batch.append(",\n");
        }

        batch.append('(');
        for (int i = 0; i < values.size(); i++) {
            if (i > 0) {
                batch.append(", ");
            }
            ResultColumn column = i < columns.size() ? columns.get(i) : null;
            batch.append(literal(values.get(i), column));
        }
        batch.append(')');

        rowsInBatch++;
        if (rowsInBatch >= rowsPerStatement) {
            flushBatch();
        }
    }

    @Override
    public void end() throws IOException {
        flushBatch();
        if (writer != null) {
            writer.flush();
        }
    }

    @Override
    public void close() throws IOException {
        if (writer != null) {
            flushBatch();
            writer.close();
            writer = null;
        }
    }

    private void flushBatch() throws IOException {
        if (rowsInBatch == 0 || writer == null) {
            return;
        }
        writer.write(batch.append(statementTerminator).append("\n").toString());
        rowsInBatch = 0;
        batch = null;
    }

    /**
     * Renders one value as a SQL literal.
     *
     * @param column the column the value came from, used to decide whether a numeric-looking string
     *               should stay unquoted
     */
    private String literal(Object value, ResultColumn column) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Boolean flag) {
            // Spelled out rather than 1/0: PostgreSQL rejects integers for a boolean column.
            return flag ? "TRUE" : "FALSE";
        }
        if (value instanceof Number number) {
            return number.toString();
        }
        if (value instanceof List<?> array) {
            // A SQL array literal is vendor-specific, so the JSON form is emitted as text. Guessing
            // at ARRAY[...] syntax would produce a statement that fails on most databases.
            return quote(String.valueOf(array));
        }

        String text = String.valueOf(value);
        if (column != null && isNumericType(column.jdbcType()) && NUMERIC_LITERAL.matcher(text).matches()) {
            return text;
        }
        return quote(text);
    }

    /** Doubles embedded single quotes, which every SQL dialect understands. */
    private static String quote(String text) {
        return "'" + text.replace("'", "''") + "'";
    }

    private static boolean isNumericType(int jdbcType) {
        return switch (jdbcType) {
            case java.sql.Types.TINYINT, java.sql.Types.SMALLINT, java.sql.Types.INTEGER,
                 java.sql.Types.BIGINT, java.sql.Types.DECIMAL, java.sql.Types.NUMERIC,
                 java.sql.Types.FLOAT, java.sql.Types.REAL, java.sql.Types.DOUBLE -> true;
            default -> false;
        };
    }
}
